version: "2"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/ci/Dockerfile
    command: npm run ci_test
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/home/nodejs/app
