version: "2"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/ci/Dockerfile
    ports:
      - 3000:3000
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EMAIL_KEY=${JWT_EMAIL_KEY}
      - CI=true
    depends_on:
      - mongo_seed
    volumes:
      - .:/home/nodejs/app
  mongo_seed:
    build:
      context: .
      dockerfile: ./dockerfiles/mongo_seed/Dockerfile
    depends_on:
      - mongo
