version: "2"
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
    web:
        build: 
            context: .
            dockerfile: ./dockerfiles/main/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - mongo
    mongo_seed:
        build: 
            context: .
            dockerfile: ./dockerfiles/mongo_seed/Dockerfile
        depends_on:
            - mongo