name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [3.4.1]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - run: npm run setup
      - run: npm run init_db
      - run: npm run ci_test
        env:
          CI: true
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EMAIL_KEY: ${{ secrets.JWT_EMAIL_KEY }}

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login - u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t api ./dockerfiles/main
      - name: Tags
        run: |
          docker tag api ${{ secrets.DOCKER_USER }}/api:${{ github.sha }}
          docker tag api ${{ secrets.DOCKER_USER }}/api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/api:latest
