name: Docker Image CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Testing CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up env and run containers
        env:
          AWS_SECRET_ACCESS_KEY:${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker-compose -f docker-compose.integration-testing.yml up --build --exit-code-from web
