# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Continuous Integration Pipeline
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run setup
    - env: $AWS_ACCESS_KEY_ID:${{secrets.AWS_ACCESS_KEY_ID}}
    - env: $AWS_SECRET_ACCESS_KEY:${{secrets.AWS_SECRET_ACCESS_KEY}}
    - env: $JWT_EMAIL_KEY:${{secrets.JWT_EMAIL_KEY}}
    - env: $JWT_SECRET_KEY:${{secrets.JWT_SECRET_KEY}}
    - run: npm run ci_test
